name: Deploy to Development

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Hostinger Dev
        uses: easingthemes/ssh-deploy@v5.1.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_DEV }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.HOSTINGER_HOST }}

          REMOTE_USER: ${{ secrets.SSH_USER_DEV }}
          TARGET: "/home/wiwatour-dev/htdocs/dev.wiwatour.com/wp-content/plugins/wiwa-tour-checkout-pro"
          EXCLUDE: "/.git/, /.github/, /.vscode/, /.gitignore, /README.md, /node_modules/, /tests/, /*.zip, /ova-tour-booking-2026/, /woocommerce-currency-switcher/, /_original_backup/, /Wiwa_Manual_de_marca.pdf, /force-reload.ps1"
