name: Create Pre-Release

on:
  push:
    tags:
      - "v*alpha*"
      - "v*beta*"
      - "v*rc*"

jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Create Pre-Release with Changelog
      - name: Create Pre-Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: true
          files: |
            wiwa-tour-checkout-pro.zip

      # 2. (Optional) Deploy to Dev Environment to ensure it matches
      - name: Deploy to Hostinger Dev
        uses: easingthemes/ssh-deploy@v5.1.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_DEV }}
          ARGS: "-rlgoDzvc -i --delete -p ${{ env.remote_port }}"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.HOSTINGER_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER_DEV }}
          remote_port: ${{ secrets.SSH_PORT || 22 }}
          TARGET: "/home/wiwatour-dev/htdocs/dev.wiwatour.com/wp-content/plugins/wiwa-tour-checkout-pro"
          EXCLUDE: "/.git/, /.github/, /.vscode/, /.gitignore, /README.md, /node_modules/, /tests/, /*.zip, /ova-tour-booking-2026/, /woocommerce-currency-switcher/, /_original_backup/, /Wiwa_Manual_de_marca.pdf, /force-reload.ps1"
